import {ArrowRight,Plus,Clock3,FileCheck2,ScanLine,Sparkles,ArrowUpRight,Check,Sun,Leaf,BookOpen} from 'lucide-react';
import {motion} from 'framer-motion';
import {Count,Heading,SectionTitle} from './ui';
import type {Assignment} from '../data';
export default function Dashboard({assignments,go,select,newAssignment}:{assignments:Assignment[];go:(p:string)=>void;select:(id:string)=>void;newAssignment:()=>void}){const papers=assignments.flatMap(a=>a.papers),pending=papers.filter(p=>!p.approved),review=pending.filter(p=>p.trust!=='green');return <>
<Heading eyebrow="YOUR TEACHING DAY, A LITTLE LIGHTER" title="Good afternoon, Malika ☀" action={<button className="primary" onClick={newAssignment}><Plus size={18}/>Grade new assignment</button>}>A little less paperwork. A little more possibility.</Heading>
<div className="dashboard-top"><motion.section className="time-hero" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><div className="hero-text"><span className="pill"><Clock3 size={14}/> YOUR TIME, BACK</span><div className="time-number"><Count value={3}/><span>h</span> <Count value={40}/><span>m</span><span className="little-spark">✧</span></div><h2>More time for what matters.</h2><p>That’s an evening of your own.<br/>And tomorrow’s lesson, already a little better.</p><div className="hero-foot"><span><span className="tiny-dot"/>Time saved this week</span><span>Illustrative demo estimate</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-sun"><Sun size={46} strokeWidth={1.1}/></div><div className="paper-back"/><div className="paper-front"><div className="paper-top"><span/><i>Tanaffus</i></div><div className="fake-line w80"/><div className="fake-line w50"/><div className="math-line">3x − 6 = 12</div><div className="math-line">3x = 18</div><div className="math-answer">x = 6 <Check size={20}/></div><div className="fake-line w80"/><div className="fake-line w50"/><div className="paper-seal"><Check size={16}/> Teacher approved</div></div><div className="float-note"><Sparkles size={17}/><div>Feedback, ready.<small>In your voice. With your say.</small></div></div><div className="leaf"><Leaf size={38} strokeWidth={1.3}/></div></div></motion.section>
<section className="focus-card"><div className="focus-heading"><span className="yellow-icon"><Sparkles size={20}/></span><span>YOUR NEXT SMALL STEP</span></div><h2>A few papers.<br/>Your expert eye.</h2><p><strong>{review.length} submissions</strong> could use a closer look. We’ve highlighted exactly where.</p><div className="avatar-stack">{['AA','JR','MI'].map(n=><span key={n}>{n}</span>)}<small>Ready for your review</small></div><button className="dark-button" onClick={()=>{select(assignments.find(a=>a.papers.some(p=>!p.approved))?.id||assignments[0].id);go('assignments')}}>Let’s review <ArrowRight size={17}/></button><span className="quiet">AI drafts. The teacher decides.</span></section></div>
<div className="stats-row">{[{icon:FileCheck2,value:assignments.filter(a=>a.papers.every(p=>p.approved)).length,label:'Assignments approved',note:'Every final decision, yours'},{icon:ScanLine,value:papers.length,label:'Papers processed',note:'Less admin. More teaching.'},{icon:Clock3,value:pending.length,label:'Awaiting approval',note:`${review.length} need a closer look`},{icon:BookOpen,value:3,label:'Active classes',note:'78 students. So much potential.'}].map((s,i)=><motion.div className="stat" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.07}} key={s.label}><div className="stat-label"><s.icon size={17}/>{s.label}</div><strong><Count value={s.value}/></strong><small>{s.note}</small></motion.div>)}</div>
<div className="dashboard-bottom"><section className="panel assignment-panel"><SectionTitle title="On your desk" action="All assignments" onClick={()=>go('assignments')}/><div className="table-head"><span>ASSIGNMENT</span><span>PROGRESS</span><span>STATUS</span><span/></div>{assignments.slice(0,4).map((a,i)=>{const done=a.papers.filter(p=>p.approved).length;return <button className="assignment-row" key={a.id} onClick={()=>{select(a.id);go('assignments')}}><span className={`assignment-icon tone-${i%3}`}><BookOpen size={20}/></span><span><strong>{a.title}</strong><small>{a.className} <span className="sep">·</span> {a.papers.length} students</small></span><span className="progress-cell"><small>{done}/{a.papers.length} approved</small><span className="progress"><i style={{width:`${done/a.papers.length*100}%`}}/></span></span><span className={`status ${done===a.papers.length?'done':'waiting'}`}>{done===a.papers.length?'Completed':'Ready to review'}</span><ArrowUpRight size={17}/></button>})}<div className="table-footer"><span className="tiny-dot"/>All demo papers analyzed. You have the final say.</div></section>
<section className="radar-teaser"><div className="section-title"><span className="eyebrow">FROM GRADING TO GROWING</span><Sparkles size={19}/></div><div className="mini-radar" aria-hidden="true"><span/><span/><span/><i/><b/></div><h2>One pattern.<br/>A better next lesson.</h2><p><strong>11 of 28 students</strong> may need another look at sign changes.</p><button className="text-button" onClick={()=>{select('algebra');go('radar')}}>Explore Mistake Radar <ArrowRight size={16}/></button></section></div>
<div className="bottom-note"><span className="brand-small">✦</span> Made for the work only you can do. <span>We’ll take care of the repetitive part.</span></div></>}
