import {useEffect,useRef, type ReactNode} from 'react';
import {Check,AlertCircle,Pencil,X,ArrowUpRight} from 'lucide-react';
import {animate,motion,useReducedMotion} from 'framer-motion';
import type {Trust} from '../data';
export function Count({value}:{value:number}){const ref=useRef<HTMLSpanElement>(null);const reduce=useReducedMotion();useEffect(()=>{if(reduce){if(ref.current)ref.current.textContent=String(value);return;}const control=animate(0,value,{duration:1.1,onUpdate:v=>{if(ref.current)ref.current.textContent=Math.round(v).toString();}});return()=>control.stop()},[value,reduce]);return <span ref={ref}>{value}</span>}
export function Badge({trust,approved=false}:{trust:Trust;approved?:boolean}){const Icon=approved?Check:trust==='green'?Check:trust==='yellow'?AlertCircle:Pencil;return <span className={`badge ${approved?'approved':trust}`}><Icon size={12}/>{approved?'Approved':trust==='green'?'High confidence':trust==='yellow'?'Needs review':'Manual grading'}</span>}
export function Heading({eyebrow,title,children,action}:{eyebrow:string;title:string;children?:ReactNode;action?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{children&&<p>{children}</p>}</div>{action}</div>}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><h3>{title}</h3><p>{children}</p></div>}
export function SectionTitle({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="section-title"><h2>{title}</h2>{action&&<button className="text-button" onClick={onClick}>{action}<ArrowUpRight size={15}/></button>}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement;ref.current?.focus();const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=ref.current?.querySelectorAll<HTMLElement>('button, input, select, textarea, a[href], [tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',fn);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',fn);document.body.style.overflow=overflow;prev?.focus()}},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><motion.div initial={{opacity:0,y:20,scale:.97}} animate={{opacity:1,y:0,scale:1}} className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><div className="section-title"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</motion.div></div>}
export function download(name:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
